move stage up for testing purposes escape table var

diff --git a/roles/generate-jenkins/templates/Jenkinsfile.j2 b/roles/generate-jenkins/templates/Jenkinsfile.j2
--- a/roles/generate-jenkins/templates/Jenkinsfile.j2
+++ b/roles/generate-jenkins/templates/Jenkinsfile.j2
@@ -372,6 +372,78 @@ pipeline {
         }
       }
     }
+    // If this is a Pull request send the CI link as a comment on it
+    stage('Pull Request Comment Test') {
+      when {
+        not {environment name: 'CHANGE_ID', value: ''}
+        environment name: 'CI', value: 'true'
+        environment name: 'EXIT_STATUS', value: ''
+      }
+      steps {
+        sh '''#! /bin/bash
+        CI_URL=https://fakedomain.fake
+        CI_JSON_URL=https://gilbnlsio2.s3.us-east-1.amazonaws.com/linuxserver/lidarr/latest/report.json
+        SHELLCHECK_URL=https://fakedomain.fake
+            # Function to retrieve JSON data from URL
+            get_json() {
+              local url=\"$1\"
+              local response=$(curl -s \"$url\")
+              if [ $? -ne 0 ]; then
+                echo \"Failed to retrieve JSON data from $url\"
+                return 1
+              fi
+              local json=$(echo \"$response\" | jq .)
+              if [ $? -ne 0 ]; then
+                echo \"Failed to parse JSON data from $url\"
+                return 1
+              fi
+              echo \"$json\"
+            }
+
+            build_table() {
+              local data=\"$1\"
+
+              # Get the keys in the JSON data
+              local keys=$(echo \"$data\" | jq -r \'to_entries | map(.key) | .[]\')
+
+              # Check if keys are empty
+              if [ -z \"$keys\" ]; then
+                echo \"JSON report data does not contain any keys or the report does not exist.\"
+                return 1
+              fi
+
+              # Build table header
+              local header=\"| Tag | Passed |\\n| --- | --- |\\n\"
+
+              # Loop through the JSON data to build the table rows
+              local rows=\"\"
+              for build in $keys; do
+                local status=$(echo \"$data\" | jq -r \".[\\"$build\\"].test_success\")
+                if [ \"$status\" = \"true\" ]; then
+                  status=\"✅\"
+                else
+                  status=\"❌\"
+                fi
+                local row=\"| \"$build\" | \"$status\" |\n\"
+                rows=\"$rows$row\"
+              done
+
+              local table=\"$header$rows\"
+              local escaped_table=$(echo \"$table\" | sed \'s/\"/\\\"/g\')
+              echo \"$escaped_table\"
+            }
+
+            # Retrieve JSON data from URL
+            data=$(get_json \"$CI_JSON_URL\")
+            # Create table from JSON data
+            table=$(build_table \"$data\")
+
+            curl -X POST -H \"Authorization: token $GITHUB_TOKEN\" \
+              -H \"Accept: application/vnd.github.v3+json\" \
+              \"https://api.github.com/repos/$LS_USER/$LS_REPO/issues/$PULL_REQUEST/comments\" \
+              -d \"{\"body\":\"(Fake Test) I am a bot, here are the test results for this PR: \\n$CI_URL\\n$SHELLCHECK_URL\\n\"$table\"\"}\"'''
+      }
+    }
 {% if project_repo_name == "docker-jenkins-builder" %}
     // Build Docker container local templating CI runs
     stage('Build-Jenkins-Builder') {
@@ -1345,7 +1417,7 @@ pipeline {
             curl -X POST -H \"Authorization: token $GITHUB_TOKEN\" \
               -H \"Accept: application/vnd.github.v3+json\" \
               \"https://api.github.com/repos/$LS_USER/$LS_REPO/issues/$PULL_REQUEST/comments\" \
-              -d \"{\"body\":\"I am a bot, here are the test results for this PR: \\n$CI_URL\\n$SHELLCHECK_URL\\n$table\"}\"'''
+              -d \"{\"body\":\"I am a bot, here are the test results for this PR: \\n$CI_URL\\n$SHELLCHECK_URL\\n\"$table\"\"}\"'''
       }
     }
 {% if project_deprecation_status %}
