single quote wrap

diff --git a/roles/generate-jenkins/templates/Jenkinsfile.j2 b/roles/generate-jenkins/templates/Jenkinsfile.j2
--- a/roles/generate-jenkins/templates/Jenkinsfile.j2
+++ b/roles/generate-jenkins/templates/Jenkinsfile.j2
@@ -379,53 +379,70 @@ pipeline {
         environment name: 'CI', value: 'true'
         environment name: 'EXIT_STATUS', value: ''
       }
-    script {
-        def get_json() {
-            //def url = "$CI_JSON_URL"
-            def CI_URL="https://fakedomain.fake"
-            def url="https://gilbnlsio2.s3.us-east-1.amazonaws.com/linuxserver/lidarr/latest/report.json"
-            def SHELLCHECK_URL="https://fakedomain.fake"
-            def response = sh(script: "curl -s \"$url\"", returnStdout: true).trim()
-            if (response) {
-                def json = sh(script: "echo '${response}' | jq .", returnStdout: true).trim()
-                if (json) {
-                    return json
-                } else {
-                    error "Failed to parse JSON data from $url"
-                }
-            } else {
-                error "Failed to retrieve JSON data from $url"
+      steps {
+        sh '''#! /bin/bash
+        CI_URL=https://fakedomain.fake
+        CI_JSON_URL=https://gilbnlsio2.s3.us-east-1.amazonaws.com/linuxserver/lidarr/latest/report.json
+        SHELLCHECK_URL=https://fakedomain.fake
+            # Function to retrieve JSON data from URL
+            get_json() {
+              local url=\"$1\"
+              local response=$(curl -s \"$url\")
+              if [ $? -ne 0 ]; then
+                echo \"Failed to retrieve JSON data from $url\"
+                return 1
+              fi
+              local json=$(echo \"$response\" | jq .)
+              if [ $? -ne 0 ]; then
+                echo \"Failed to parse JSON data from $url\"
+                return 1
+              fi
+              echo \"$json\"
             }
-        }
-        def build_table(data) {
-            def keys = sh(script: "echo '${data}' | jq -r 'to_entries | map(.key) | .[]'", returnStdout: true).trim()
-            if (keys) {
-                def header = "| Tag | Passed |\n| --- | --- |\n"
-                def rows = ""
-                keys.tokenize().each { build ->
-                    def status = sh(script: "echo '${data}' | jq -r '.[\"${build}\"].test_success'", returnStdout: true).trim()
-                    status = status == 'true' ? ':white_check_mark:' : ':x:'
-                    def row = "| ${build} | ${status} |\n"
-                    rows += row
-                }
-                def table = header + rows
-                return table.replaceAll(/"/, '\\\\"')
-            } else {
-                error "JSON report data does not contain any keys or the report does not exist."
-            }
-        }
-        def data = get_json()
-        def table = build_table(data)
-        def payload = "{\"body\":\"I am a bot, here are the test results for this PR: \\n${CI_URL}\\n${SHELLCHECK_URL}\\n${table}\"}"
-        def apiEndpoint = "https://api.github.com/repos/${LS_USER}/${LS_REPO}/issues/${PULL_REQUEST}/comments"
 
-        sh(script: """
-            curl -X POST -H 'Authorization: token ${GITHUB_TOKEN}' \\
-                -H 'Accept: application/vnd.github.v3+json' \\
-                '${apiEndpoint}' \\
-                -d '${payload}'
-        """)
-    }
+            build_table() {
+              local data=\"$1\"
+
+              # Get the keys in the JSON data
+              local keys=$(echo \"$data\" | jq -r \'to_entries | map(.key) | .[]\')
+
+              # Check if keys are empty
+              if [ -z \"$keys\" ]; then
+                echo \"JSON report data does not contain any keys or the report does not exist.\"
+                return 1
+              fi
+
+              # Build table header
+              local header=\"| Tag | Passed |\\n| --- | --- |\\n\"
+
+              # Loop through the JSON data to build the table rows
+              local rows=\"\"
+              for build in $keys; do
+                local status=$(echo \"$data\" | jq -r \".[\\"$build\\"].test_success\")
+                if [ \"$status\" = \"true\" ]; then
+                  status=\"✅\"
+                else
+                  status=\"❌\"
+                fi
+                local row=\"| \"$build\" | \"$status\" |\n\"
+                rows=\"$rows$row\"
+              done
+
+              local table=\"$header$rows\"
+              local escaped_table=$(echo \"$table\" | sed \'s/\"/\\\"/g\')
+              echo \"$escaped_table\"
+            }
+
+            # Retrieve JSON data from URL
+            data=$(get_json \"$CI_JSON_URL\")
+            # Create table from JSON data
+            table=$(build_table \"$data\")
+
+            curl -H "Authorization: token ${GITHUB_TOKEN}" 
+            -X POST https://api.github.com/repos/${LS_USER}/${LS_REPO}/issues/${PULL_REQUEST}/comments \
+            -d '{"body": "TEST I am a bot, here are the test results for this PR: \\n'${CI_URL}' \\n'${SHELLCHECK_URL}'\\n'${table}'"}
+        '''
+      }
     }
 {% if project_repo_name == "docker-jenkins-builder" %}
     // Build Docker container local templating CI runs
